version: "3"

networks:
  plx-network:
    driver: bridge

services:
  postgres:
    build: ./images/postgres/local
    restart: always
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
      - ./shared:/shared
    ports:
      - "5432:5432"
    networks:
      - plx-network

  mongo:
    build: ./images/mongo/local
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=docker
      - MONGODB_DATABASE=
    volumes:
      - ./volumes/mongo-data:/bitnami/mongodb/data
      - ./shared:/shared
    ports:
      - "27017:27017"
    networks:
      - plx-network
